theme: minima
title: Hint Tours
description: What is this? I just scanned a random QR Code! Hint Tours is a Self guide tour with clues which guides the users through the city! Head to the main page to go on your own tour!


header_pages:
 - literacy.markdown
 - faq.markdown
 - contact.markdown
